export interface CRATestItem {
  code: string
  name: string
  catalogueRate: number
  discount: number
  realizedRevenue: number
  c1Incentive: number
  category: string
  technology: string
  sample: string
}

export const CRA_TESTS: CRATestItem[] = [
  {
    code: "CUA",
    name: "COMPLETE URINE ANALYSIS",
    catalogueRate: 300.0,
    discount: 60.0,
    realizedRevenue: 240.0,
    c1Incentive: 72.0,
    category: "Complete Urine Analysis",
    technology: "Microscopy",
    sample: "Urine"
  },
  {
    code: "H6",
    name: "HEMOGRAM - 6 PART (DIFF)",
    catalogueRate: 300.0,
    discount: 60.0,
    realizedRevenue: 240.0,
    c1Incentive: 72.0,
    category: "Hematology",
    technology: "Hematology Analyzer",
    sample: "EDTA"
  },
  {
    code: "SHBG",
    name: "SEX HORMONE BINDING GLOBULIN (SHBG)",
    catalogueRate: 500.0,
    discount: 100.0,
    realizedRevenue: 400.0,
    c1Incentive: 120.0,
    category: "Reproductive & Endocrinology",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "AMYL",
    name: "AMYLASE",
    catalogueRate: 200.0,
    discount: 40.0,
    realizedRevenue: 160.0,
    c1Incentive: 48.0,
    category: "General Biochemistry",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "CCM_M",
    name: "CYTOMEGALO VIRUS (CMV) - IGM",
    catalogueRate: 350.0,
    discount: 70.0,
    realizedRevenue: 280.0,
    c1Incentive: 84.0,
    category: "Infectious Disease Serology",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "AFP",
    name: "ALPHA FETO PROTEIN (AFP)",
    catalogueRate: 550.0,
    discount: 110.0,
    realizedRevenue: 440.0,
    c1Incentive: 132.0,
    category: "Tumor Markers",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "INSFA",
    name: "INSULIN - FASTING",
    catalogueRate: 300.0,
    discount: 60.0,
    realizedRevenue: 240.0,
    c1Incentive: 72.0,
    category: "Diabetes",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "T4",
    name: "TOTAL THYROXINE (T4)",
    catalogueRate: 100.0,
    discount: 20.0,
    realizedRevenue: 80.0,
    c1Incentive: 24.0,
    category: "Thyroid",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "APOA",
    name: "APOLIPOPROTEIN - A1 (APO-A1)",
    catalogueRate: 200.0,
    discount: 40.0,
    realizedRevenue: 160.0,
    c1Incentive: 48.0,
    category: "Lipid Profile",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "BUN",
    name: "BLOOD UREA NITROGEN (BUN)",
    catalogueRate: 100.0,
    discount: 20.0,
    realizedRevenue: 80.0,
    c1Incentive: 24.0,
    category: "Kidney Function",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "LPA",
    name: "LIPOPROTEIN (A)",
    catalogueRate: 200.0,
    discount: 40.0,
    realizedRevenue: 160.0,
    c1Incentive: 48.0,
    category: "Lipid Profile",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "AMA",
    name: "ANTI MICROSOMAL ANTIBODY (AMA)",
    catalogueRate: 500.0,
    discount: 100.0,
    realizedRevenue: 400.0,
    c1Incentive: 120.0,
    category: "Thyroid",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "LH",
    name: "LUTEINISING HORMONE (LH)",
    catalogueRate: 250.0,
    discount: 50.0,
    realizedRevenue: 200.0,
    c1Incentive: 60.0,
    category: "Reproductive & Endocrinology",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "AMH",
    name: "ANTI MULLERIAN HORMONE (AMH)",
    catalogueRate: 750.0,
    discount: 150.0,
    realizedRevenue: 600.0,
    c1Incentive: 180.0,
    category: "Reproductive & Endocrinology",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "NPBNP",
    name: "NT-PROBNP",
    catalogueRate: 650.0,
    discount: 130.0,
    realizedRevenue: 520.0,
    c1Incentive: 156.0,
    category: "Cardiac",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "SGOT",
    name: "ASPARTATE AMINOTRANSFERASE (SGOT )",
    catalogueRate: 100.0,
    discount: 20.0,
    realizedRevenue: 80.0,
    c1Incentive: 24.0,
    category: "Liver Function",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "CORT",
    name: "CORTISOL",
    catalogueRate: 450.0,
    discount: 90.0,
    realizedRevenue: 360.0,
    c1Incentive: 108.0,
    category: "Pituitary & Growth",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "ACTH",
    name: "ACTH",
    catalogueRate: 700.0,
    discount: 140.0,
    realizedRevenue: 560.0,
    c1Incentive: 168.0,
    category: "Pituitary & Growth",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "PPBS",
    name: "POSTPRANDIAL BLOOD SUGAR",
    catalogueRate: 100.0,
    discount: 20.0,
    realizedRevenue: 80.0,
    c1Incentive: 24.0,
    category: "Diabetes",
    technology: "Photometry",
    sample: "Fluoride"
  },
  {
    code: "FOLI",
    name: "FOLATE",
    catalogueRate: 450.0,
    discount: 90.0,
    realizedRevenue: 360.0,
    c1Incentive: 108.0,
    category: "Vitamins",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "CHS1G",
    name: "HERPES SIMPLEX VIRUS I (HSV)-IGG",
    catalogueRate: 350.0,
    discount: 70.0,
    realizedRevenue: 280.0,
    c1Incentive: 84.0,
    category: "Pathology Profile",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "EAG",
    name: "HEPATITIS B ENVELOPE ANTIGEN (HBEAG)",
    catalogueRate: 450.0,
    discount: 90.0,
    realizedRevenue: 360.0,
    c1Incentive: 108.0,
    category: "Infectious Disease Serology",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "HCHO",
    name: "HDL CHOLESTEROL - DIRECT",
    catalogueRate: 100.0,
    discount: 20.0,
    realizedRevenue: 80.0,
    c1Incentive: 24.0,
    category: "Lipid Profile",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "PTH",
    name: "INTACT PARATHYROID HORMONE (PTH)",
    catalogueRate: 650.0,
    discount: 130.0,
    realizedRevenue: 520.0,
    c1Incentive: 156.0,
    category: "Bone Metabolism",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "VITDC",
    name: "25-OH VITAMIN D (TOTAL)",
    catalogueRate: 400.0,
    discount: 80.0,
    realizedRevenue: 320.0,
    c1Incentive: 96.0,
    category: "Vitamins",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "GGT",
    name: "GAMMA GLUTAMYL TRANSFERASE (GGT)",
    catalogueRate: 100.0,
    discount: 20.0,
    realizedRevenue: 80.0,
    c1Incentive: 24.0,
    category: "Liver Function",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "CA19-9",
    name: "CA19-9",
    catalogueRate: 500.0,
    discount: 100.0,
    realizedRevenue: 400.0,
    c1Incentive: 120.0,
    category: "Tumor Markers",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "IRON",
    name: "IRON",
    catalogueRate: 100.0,
    discount: 20.0,
    realizedRevenue: 80.0,
    c1Incentive: 24.0,
    category: "Iron Studies",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "TEST",
    name: "TESTOSTERONE",
    catalogueRate: 300.0,
    discount: 60.0,
    realizedRevenue: 240.0,
    c1Incentive: 72.0,
    category: "Reproductive & Endocrinology",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "FT3",
    name: "FREE TRIIODOTHYRONINE (FT3)",
    catalogueRate: 100.0,
    discount: 20.0,
    realizedRevenue: 80.0,
    c1Incentive: 24.0,
    category: "Thyroid",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "CEA",
    name: "CARCINO EMBRYONIC ANTIGEN (CEA)",
    catalogueRate: 550.0,
    discount: 110.0,
    realizedRevenue: 440.0,
    c1Incentive: 132.0,
    category: "Tumor Markers",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "CPEP",
    name: "C-PEPTIDE",
    catalogueRate: 500.0,
    discount: 100.0,
    realizedRevenue: 400.0,
    c1Incentive: 120.0,
    category: "Diabetes",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "BILD",
    name: "BILIRUBIN -DIRECT",
    catalogueRate: 100.0,
    discount: 20.0,
    realizedRevenue: 80.0,
    c1Incentive: 24.0,
    category: "Liver Function",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "HSCRP",
    name: "HIGH SENSITIVITY C-REACTIVE PROTEIN (HS-CRP)",
    catalogueRate: 200.0,
    discount: 40.0,
    realizedRevenue: 160.0,
    c1Incentive: 48.0,
    category: "General Biochemistry",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "CHIV",
    name: "HIV P24 AG/AB",
    catalogueRate: 400.0,
    discount: 80.0,
    realizedRevenue: 320.0,
    c1Incentive: 96.0,
    category: "Infectious Disease Serology",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "BHCG",
    name: "BETA HCG",
    catalogueRate: 300.0,
    discount: 60.0,
    realizedRevenue: 240.0,
    c1Incentive: 72.0,
    category: "Pregnancy",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "PRL",
    name: "PROLACTIN (PRL)",
    catalogueRate: 250.0,
    discount: 50.0,
    realizedRevenue: 200.0,
    c1Incentive: 60.0,
    category: "Reproductive & Endocrinology",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "CALCT",
    name: "CALCITONIN",
    catalogueRate: 600.0,
    discount: 120.0,
    realizedRevenue: 480.0,
    c1Incentive: 144.0,
    category: "Bone Metabolism",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "CTX_G",
    name: "TOXO GONDII - IGG",
    catalogueRate: 350.0,
    discount: 70.0,
    realizedRevenue: 280.0,
    c1Incentive: 84.0,
    category: "Infectious Disease Serology",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "APOB",
    name: "APOLIPOPROTEIN - B (APO-B)",
    catalogueRate: 200.0,
    discount: 40.0,
    realizedRevenue: 160.0,
    c1Incentive: 48.0,
    category: "Lipid Profile",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "PHOS",
    name: "PHOSPHOROUS",
    catalogueRate: 200.0,
    discount: 40.0,
    realizedRevenue: 160.0,
    c1Incentive: 48.0,
    category: "General Biochemistry",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "SCRE",
    name: "CREATININE - SERUM",
    catalogueRate: 100.0,
    discount: 20.0,
    realizedRevenue: 80.0,
    c1Incentive: 24.0,
    category: "Kidney Function",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "CA125",
    name: "CA125",
    catalogueRate: 550.0,
    discount: 110.0,
    realizedRevenue: 440.0,
    c1Incentive: 132.0,
    category: "Tumor Markers",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "T3",
    name: "TOTAL TRIIODOTHYRONINE (T3)",
    catalogueRate: 100.0,
    discount: 20.0,
    realizedRevenue: 80.0,
    c1Incentive: 24.0,
    category: "Thyroid",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "CHS2G",
    name: "HERPES SIMPLEX VIRUS II (HSV)-IGG",
    catalogueRate: 350.0,
    discount: 70.0,
    realizedRevenue: 280.0,
    c1Incentive: 84.0,
    category: "Infectious Disease Serology",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "SGPT",
    name: "ALANINE TRANSAMINASE (SGPT)",
    catalogueRate: 100.0,
    discount: 20.0,
    realizedRevenue: 80.0,
    c1Incentive: 24.0,
    category: "Liver Function",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "FBHCG",
    name: "FREE BETA HCG",
    catalogueRate: 450.0,
    discount: 90.0,
    realizedRevenue: 360.0,
    c1Incentive: 108.0,
    category: "Pregnancy",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "PROG",
    name: "PROGESTERONE",
    catalogueRate: 350.0,
    discount: 70.0,
    realizedRevenue: 280.0,
    c1Incentive: 84.0,
    category: "Reproductive & Endocrinology",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "CHOL",
    name: "TOTAL CHOLESTEROL",
    catalogueRate: 100.0,
    discount: 20.0,
    realizedRevenue: 80.0,
    c1Incentive: 24.0,
    category: "Lipid Profile",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "SAG",
    name: "HEPATITIS B SURFACE ANTIGEN (HBSAG)",
    catalogueRate: 200.0,
    discount: 40.0,
    realizedRevenue: 160.0,
    c1Incentive: 48.0,
    category: "Infectious Disease Serology",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "TIGE",
    name: "TOTAL IGE",
    catalogueRate: 300.0,
    discount: 60.0,
    realizedRevenue: 240.0,
    c1Incentive: 72.0,
    category: "Allergy & Immunology",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "ALKP",
    name: "ALKALINE PHOSPHATASE",
    catalogueRate: 100.0,
    discount: 20.0,
    realizedRevenue: 80.0,
    c1Incentive: 24.0,
    category: "Liver Function",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "LASE",
    name: "LIPASE",
    catalogueRate: 300.0,
    discount: 60.0,
    realizedRevenue: 240.0,
    c1Incentive: 72.0,
    category: "General Biochemistry",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "AHCV",
    name: "ANTI HEPATITIS C VIRUS (ANTI HCV) - TOTAL",
    catalogueRate: 600.0,
    discount: 120.0,
    realizedRevenue: 480.0,
    c1Incentive: 144.0,
    category: "Infectious Disease Serology",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "VITB",
    name: "VITAMIN B-12",
    catalogueRate: 400.0,
    discount: 80.0,
    realizedRevenue: 320.0,
    c1Incentive: 96.0,
    category: "Vitamins",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "ATG",
    name: "ANTI THYROGLOBULIN ANTIBODY (ATG)",
    catalogueRate: 600.0,
    discount: 120.0,
    realizedRevenue: 480.0,
    c1Incentive: 144.0,
    category: "Thyroid",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "HBCM",
    name: "ANTI HEPATITIS B CORE ANTIGEN (AHBC) - IGM",
    catalogueRate: 700.0,
    discount: 140.0,
    realizedRevenue: 560.0,
    c1Incentive: 168.0,
    category: "Infectious Disease Serology",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "DHEA",
    name: "DHEA - SULPHATE (DHEAS)",
    catalogueRate: 600.0,
    discount: 120.0,
    realizedRevenue: 480.0,
    c1Incentive: 144.0,
    category: "Reproductive & Endocrinology",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "E2",
    name: "ESTRADIOL/OESTROGEN (E2)",
    catalogueRate: 300.0,
    discount: 60.0,
    realizedRevenue: 240.0,
    c1Incentive: 72.0,
    category: "Reproductive & Endocrinology",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "CTX_M",
    name: "TOXO GONDII - IGM",
    catalogueRate: 350.0,
    discount: 70.0,
    realizedRevenue: 280.0,
    c1Incentive: 84.0,
    category: "Infectious Disease Serology",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "BILT",
    name: "BILIRUBIN - TOTAL",
    catalogueRate: 100.0,
    discount: 20.0,
    realizedRevenue: 80.0,
    c1Incentive: 24.0,
    category: "Liver Function",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "CCM_G",
    name: "CYTOMEGALO VIRUS (CMV) - IGG",
    catalogueRate: 350.0,
    discount: 70.0,
    realizedRevenue: 280.0,
    c1Incentive: 84.0,
    category: "Infectious Disease Serology",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "FBS",
    name: "FASTING BLOOD SUGAR",
    catalogueRate: 100.0,
    discount: 20.0,
    realizedRevenue: 80.0,
    c1Incentive: 24.0,
    category: "Diabetes",
    technology: "Photometry",
    sample: "Fluoride"
  },
  {
    code: "HSTNI",
    name: "HIGH SENSITIVITY TROPONIN I",
    catalogueRate: 600.0,
    discount: 120.0,
    realizedRevenue: 480.0,
    c1Incentive: 144.0,
    category: "Cardiac",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "TSH",
    name: "THYROID STIMULATING HORMONE (TSH)",
    catalogueRate: 100.0,
    discount: 20.0,
    realizedRevenue: 80.0,
    c1Incentive: 24.0,
    category: "Thyroid",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "FSH",
    name: "FOLLICLE STIMULATING HORMONE (FSH)",
    catalogueRate: 250.0,
    discount: 50.0,
    realizedRevenue: 200.0,
    c1Incentive: 60.0,
    category: "Reproductive & Endocrinology",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "HBA",
    name: "HBA1C",
    catalogueRate: 300.0,
    discount: 60.0,
    realizedRevenue: 240.0,
    c1Incentive: 72.0,
    category: "Diabetes",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "TRIG",
    name: "TRIGLYCERIDES",
    catalogueRate: 100.0,
    discount: 20.0,
    realizedRevenue: 80.0,
    c1Incentive: 24.0,
    category: "Lipid Profile",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "PSA",
    name: "PROSTATE SPECIFIC ANTIGEN (PSA)",
    catalogueRate: 300.0,
    discount: 60.0,
    realizedRevenue: 240.0,
    c1Incentive: 72.0,
    category: "Tumor Markers",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "CALC",
    name: "CALCIUM",
    catalogueRate: 100.0,
    discount: 20.0,
    realizedRevenue: 80.0,
    c1Incentive: 24.0,
    category: "General Biochemistry",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "CRP",
    name: "C-REACTIVE PROTEIN (CRP)",
    catalogueRate: 100.0,
    discount: 20.0,
    realizedRevenue: 80.0,
    c1Incentive: 24.0,
    category: "General Biochemistry",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "FERR",
    name: "FERRITIN",
    catalogueRate: 300.0,
    discount: 60.0,
    realizedRevenue: 240.0,
    c1Incentive: 72.0,
    category: "Iron Studies",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "HBST",
    name: "HEPATITS B SURFACE ANTIBODY (ANTI-HBS) - TOTAL",
    catalogueRate: 600.0,
    discount: 120.0,
    realizedRevenue: 480.0,
    c1Incentive: 144.0,
    category: "Infectious Disease Serology",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "HGH",
    name: "HUMAN GROWTH HORMONE (HGH)",
    catalogueRate: 450.0,
    discount: 90.0,
    realizedRevenue: 360.0,
    c1Incentive: 108.0,
    category: "Pituitary & Growth",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "FPSA",
    name: "FREE PSA",
    catalogueRate: 550.0,
    discount: 110.0,
    realizedRevenue: 440.0,
    c1Incentive: 132.0,
    category: "Tumor Markers",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "AHBE",
    name: "ANTI HEPATITIS B ENVELOPE ANTIGEN (AHBE) -TOTAL",
    catalogueRate: 450.0,
    discount: 90.0,
    realizedRevenue: 360.0,
    c1Incentive: 108.0,
    category: "Infectious Disease Serology",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "CA15-3",
    name: "CA15-3",
    catalogueRate: 500.0,
    discount: 100.0,
    realizedRevenue: 400.0,
    c1Incentive: 120.0,
    category: "Tumor Markers",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "RBS",
    name: "RANDOM BLOOD SUGAR",
    catalogueRate: 100.0,
    discount: 20.0,
    realizedRevenue: 80.0,
    c1Incentive: 24.0,
    category: "Diabetes",
    technology: "Photometry",
    sample: "Fluoride"
  },
  {
    code: "ACCP",
    name: "ANTI - CCP (ACCP)",
    catalogueRate: 650.0,
    discount: 130.0,
    realizedRevenue: 520.0,
    c1Incentive: 156.0,
    category: "Autoimmune",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "CRB_M",
    name: "RUBELLA - IGM",
    catalogueRate: 350.0,
    discount: 70.0,
    realizedRevenue: 280.0,
    c1Incentive: 84.0,
    category: "Infectious Disease Serology",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "UREA",
    name: "UREA",
    catalogueRate: 100.0,
    discount: 20.0,
    realizedRevenue: 80.0,
    c1Incentive: 24.0,
    category: "Kidney Function",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "LDL",
    name: "LDL CHOLESTEROL - DIRECT",
    catalogueRate: 100.0,
    discount: 20.0,
    realizedRevenue: 80.0,
    c1Incentive: 24.0,
    category: "Lipid Profile",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "TIBC",
    name: "TOTAL IRON BINDING CAPACITY (TIBC)",
    catalogueRate: 200.0,
    discount: 40.0,
    realizedRevenue: 160.0,
    c1Incentive: 48.0,
    category: "Iron Studies",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "SALB",
    name: "ALBUMIN - SERUM",
    catalogueRate: 100.0,
    discount: 20.0,
    realizedRevenue: 80.0,
    c1Incentive: 24.0,
    category: "Liver Function",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "HBCT",
    name: "ANTI HEPATITIS B CORE ANTIGEN (AHBC) - TOTAL",
    catalogueRate: 600.0,
    discount: 120.0,
    realizedRevenue: 480.0,
    c1Incentive: 144.0,
    category: "Infectious Disease Serology",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "ANDR",
    name: "ANDROSTENEDIONE (A4)",
    catalogueRate: 750.0,
    discount: 150.0,
    realizedRevenue: 600.0,
    c1Incentive: 180.0,
    category: "Reproductive & Endocrinology",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "URIC",
    name: "URIC ACID",
    catalogueRate: 100.0,
    discount: 20.0,
    realizedRevenue: 80.0,
    c1Incentive: 24.0,
    category: "Kidney Function",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "FT4",
    name: "FREE THYROXINE (FT4)",
    catalogueRate: 100.0,
    discount: 20.0,
    realizedRevenue: 80.0,
    c1Incentive: 24.0,
    category: "Thyroid",
    technology: "E.C.L.I.A",
    sample: "Serum"
  },
  {
    code: "SYPHILIS",
    name: "ANTI – SYPHILIS ANTIBODY",
    catalogueRate: 550.0,
    discount: 110.0,
    realizedRevenue: 440.0,
    c1Incentive: 132.0,
    category: "Infectious Disease Serology",
    technology: "Photometry",
    sample: "Serum"
  },
  {
    code: "PROT",
    name: "PROTEIN - TOTAL",
    catalogueRate: 100.0,
    discount: 20.0,
    realizedRevenue: 80.0,
    c1Incentive: 24.0,
    category: "Liver Function",
    technology: "Photometry",
    sample: "Serum"
  }
]
